# Generated by Django 5.1.1 on 2024-09-14 23:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_votaciones_id_usuario_usuariosextra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votaciones',
            unique_together={('id_usuario', 'id_obra')},
        ),
    ]
