# Generated by Django 5.1.1 on 2024-09-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_rename_fecha_eventos_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha_final',
            field=models.DateField(default='2030-01-01'),
        ),
    ]
