# Generated by Django 5.1.1 on 2024-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_eventos_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='qr_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
