# Generated by Django 5.1.1 on 2024-09-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_escultores_foto_perfil_votaciones_id_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escultores',
            name='foto_perfil',
        ),
    ]
