# Generated by Django 5.1.1 on 2024-09-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_remove_votaciones_id_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
