# Generated by Django 5.1.1 on 2024-09-28 21:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_delete_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='escultores',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
