# Generated by Django 5.1.1 on 2024-09-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_escultores_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosextra',
            old_name='fecha_nacimiento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='usuariosextra',
            old_name='pais',
            new_name='country',
        ),
    ]
