# Generated by Django 5.1.1 on 2024-10-16 19:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_votaciones_id_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='foto1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='res.cloudinary.com/dq1vfo4c8/image'),
        ),
        migrations.AddField(
            model_name='obras',
            name='foto2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='res.cloudinary.com/dq1vfo4c8/image'),
        ),
    ]
