# Generated by Django 5.1.1 on 2024-12-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_remove_obras_codigo_qr_remove_obras_qr_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='escultores',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escultores',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escultores',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
