# Generated by Django 5.1.1 on 2024-09-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_obras_codigo_qr_obras_qr_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='escultores',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='votaciones',
            name='id_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.eventos'),
            preserve_default=False,
        ),
    ]
