# Generated by Django 5.1.1 on 2024-11-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_eventos_foto1_eventos_foto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='codigo_qr',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='qr_expiracion',
        ),
    ]
